config/routes.rb
DateTracker::Application.routes.draw do
  root :to => "trackers#index"
  resources :trackers

end

app/models/tracker.rb
class Tracker < ActiveRecord::Base
  attr_accessible :date, :name, :description

  validates :date, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trackers_controller.rb
class TrackersController < ApplicationController
  def index
    @tracker = Tracker.where(['date <= ?', Date.today]).order('date desc')
  end

  def new
    @tracker = Tracker.new
  end

  def create
    @tracker = Tracker.new(params[:tracker])
    if @tracker.save
      flash[:notice] = "Tracker has been created."
      redirect_to @tracker
    else
      flash[:alert] = "Tracker has not been created."
      render :action => "new"
    end
  end

  def show
    @tracker = Tracker.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(*parts)
    unless parts.empty?
      content_for :title do
        (parts << "Date_Tracker").join(" - ")
      end
    end
  end
end

app/helpers/trackers_helper.rb
module TrackersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>
    <% if content_for?(:title) %>
      <%= yield(:title) %>
    <% else %>
      Date_Tracker
    <% end %>
  </title>

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% flash.each do |key, value| %>

  <div class='flash' id='<%= key %>'>
    <%= value %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/trackers/index.html.erb
<h2>Important Date Tracker</h2>
<ul>
  <% @tracker.each do |tracker| %>
    <li><%= link_to "#{tracker.date}", tracker %></li>
  <% end %>
</ul>

<%= link_to "Enter New Date", new_tracker_path %>

app/views/trackers/new.html.erb
<h2>New Tracker</h2>
<%= form_for(@tracker) do |f| %>
<%= f.error_messages %>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  <%= f.submit "Add Date" %>
<% end %>

<%= link_to "Back to List", trackers_path %>

app/views/trackers/show.html.erb
<% title(@tracker.name, "Trackers") %>
<h2><%= @tracker.name %></h2>
<p><%= @tracker.date %></p>
<p><%= @tracker.description %></p>

<%= link_to "Back to List", trackers_path %>